name: Build usb-trigger for macOS (arm64 and amd64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile usb-trigger for both architectures
      run: |
        mkdir -p bin
        clang -arch x86_64 -framework IOKit -framework Foundation -o bin/usb-trigger-x86_64 usb-trigger.m
        clang -arch arm64 -framework IOKit -framework Foundation -o bin/usb-trigger-arm64 usb-trigger.m

    - name: Upload usb-trigger binaries as artifacts
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v4
      with:
        name: usb-trigger-binaries
        path: bin/

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*
